apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: myphpapp
spec:
  ports:
    - port: 3306
  selector:
    app: myphpapp
    tier: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: myphpapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myphpapp-mariadb
  labels:
    app: myphpapp
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: myphpapp
      tier: db
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myphpapp
        tier: db
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: repository.lab.local:5000/db
        name: myphpapp-mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: VMware1!
          #valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password
        - name: MYSQL_DATABASE
          value: demo
        - name: MYSQL_USER
          value: demouser
        - name: MYSQL_PASSWORD
          value: VMware1!
        
        ports:
        - containerPort: 3306
          name: mariadb
        imagePullPolicy: Always
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
        #command: ["/bin/bash"]
        #args: ["-c","sleep 1000", "mysql -u root -pVMware1! -h localhost demo < /tmp/employees.sql"]
        #args: ["echo ola"]
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
   name: myphpapp-mariadb
spec:
   ingress:
   - from:
     - podSelector: 
         matchLabels:
          app: myphpapp
          tier: backend
     ports:
     - protocol: TCP
       port: 3306
   egress:
   podSelector:
     matchLabels:
      app: myphpapp
      tier: db
   policyTypes:

